services:
 postgres:
  image: postgres
  container_name: postgres
  restart: always
  environment:
   POSTGRES_PASSWORD: root
   POSTGRES_USER: admin
   POSTGRES_DB: messenger
  ports:
   - "5432:5432"
  volumes:
   - postgres_data:/var/lib/postgresql/data
  networks:
   - messenger
 pgadmin:
  container_name: pgadmin
  image: dpage/pgadmin4
  restart: always
  environment:
   PGADMIN_DEFAULT_EMAIL: admin@admin.com
   PGADMIN_DEFAULT_PASSWORD: root
  ports:
   - "5050:80"
  volumes:
   - pgadmin:/var/lib/pgadmin
  networks:
   - messenger
 redis:
  image: redis:latest
  restart: always
  container_name: redis
  hostname: redis
  ports:
   - "6379:6379"
  volumes:
   - redis:/var/lib/redis
  networks:
   - messenger
 messenger:
  container_name: messenger
  image: messenger
  restart: always
  environment:
   SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/messenger
   SPRING_DATASOURCE_USERNAME: admin
   SPRING_DATASOURCE_PASSWORD: root
  ports:
   - "8080:8080"
  networks:
   - messenger
  depends_on:
   - postgres
   - redis
volumes:
 postgres_data:
 pgadmin:
 redis:
networks:
 messenger:
  
